{% set name = 'stsci.sphere' %}
{% set version = environ.get("GIT_DESCRIBE_TAG", "0.0.0")
    +".dev"
    +environ.get("GIT_DESCRIBE_NUMBER", "0") %}
{% set number = '0' %}

about:
    home: http://www.stsci.edu/institute/software_hardware
    license: GPL
    summary: stsci.sphere
build:
    number: {{ number }}
    preserve_egg_dir: 'yes'
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - astropy >=1.1
    - matplotlib
    - relic >=1.0.3
    - stsci.sphinxext
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - astropy >=1.1
    - matplotlib
    - stsci.sphinxext
    - numpy x.x
    - python x.x
source:
    git_url: ssh://git@bitbucket.org/stsci_ssb/stsci.sphere
    git_branch: setuptools-conversion
test:
    imports:
    - stsci.sphere
