{% set name = 'nictools' %}
{% set version = environ.get("GIT_DESCRIBE_TAG", "0.0.0")
    +".dev"
    +environ.get("GIT_DESCRIBE_NUMBER", "0") %}
{% set number = '0' %}

about:
    home: https://github.com/jhunkeler/nictools
    summary: nictools
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - astropy >=1.1
    - relic >=1.0.3
    - scipy
    - stsci.sphinxext
    - stsci.tools
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - astropy >=1.1
    - scipy
    - stsci.sphinxext
    - stsci.tools
    - numpy x.x
    - python x.x
source:
    git_url: https://github.com/jhunkeler/nictools
    git_branch: setuptools-conversion
test:
    imports:
    - nictools
