{% set name = 'pyraf' %}
{% set version = environ.get("GIT_DESCRIBE_TAG", "0.0.0")
    +".dev"
    +environ.get("GIT_DESCRIBE_NUMBER", "0") %}
{% set number = '0' %}

about:
    home: https://github.com/jhunkeler/pyraf
    license: BSD
    summary: pyraf
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - astropy >=1.1
    - ipython
    - relic >=1.0.3
    - stsci.tools
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - astropy >=1.1
    - ipython
    - stsci.tools
    - numpy x.x
    - python x.x
source:
    git_url: https://github.com/jhunkeler/pyraf
    git_branch: setuptools-conversion
test:
    commands:
    - pyraf --help
