{% set name = 'astrolib.coords' %}
{% set version = environ.get("GIT_DESCRIBE_TAG", "0.0.0")
    +".dev"
    +environ.get("GIT_DESCRIBE_NUMBER", "0") %}
{% set number = '0' %}

about:
    home: https://github.com/jhunkeler/astrolib.coords.git
    license: BSD
    summary: astrolib.coords
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - relic >=1.0.3
    - setuptools
    - nose
    - numpy x.x
    - python x.x
    run:
    - nose
    - numpy x.x
    - python x.x
source:
    git_url: https://github.com/jhunkeler/astrolib.coords.git/
    git_branch: setuptools-conversion
test:
    imports:
    - astrolib.coords
