{% set name = 'stsci.convolve' %}
{% set version = environ.get("GIT_DESCRIBE_TAG", "0.0.0")
    +".dev"
    +environ.get("GIT_DESCRIBE_NUMBER", "0") %}
{% set number = '0' %}

about:
    home: https://github.com/embray/stsci.convolve
    license: GPL
    summary: stsci.convolve
build:
    number: {{ number }}
    preserve_egg_dir: 'yes'
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - relic >=1.0.3
    - nose
    - stsci.sphinxext
    - numpy x.x
    - python x.x
    run:
    - nose
    - stsci.sphinxext
    - numpy x.x
    - python x.x
source:
    git_url: https://github.com/jhunkeler/stsci.convolve
    git_branch: setuptools-conversion
test:
    imports:
    - stsci.convolve
