{% set name = 'pysynphot' %}
{% set version = environ.get("GIT_DESCRIBE_TAG", "0.0.0")
    +".dev"
    +environ.get("GIT_DESCRIBE_NUMBER", "0") %}
{% set number = '0' %}

about:
    home: https://github.com/jhunkeler/pysynphot
    license: BSD
    summary: pysynphot
build:
    number: {{ number }}
    #preserve_egg_dir: 'yes'
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - nose
    - astropy >=1.1
    - cython
    - matplotlib
    - relic >=1.0.3
    - stsci.distutils
    - stsci.sphinxext
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - nose
    - astropy >=1.1
    - cython
    - matplotlib
    - stsci.sphinxext
    - numpy x.x
    - python x.x
source:
    git_url: https://github.com/jhunkeler/pysynphot
    #git_branch: setuptools-conversion
