{% set name = 'acstools' %}
{% set version = environ.get("GIT_DESCRIBE_TAG", "0.0.0")
    +".dev"
    +environ.get("GIT_DESCRIBE_NUMBER", "0") %}
{% set number = '0' %}

about:
    home: https://github.com/jhunkeler/acstools
    license: BSD
    summary: acstools
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - astropy >=1.1
    - dask
    - scipy
    - scikit-image
    - matplotlib
    - nose
    - relic >=1.0.3
    - stsci.imagestats
    - stsci.tools
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - astropy >=1.1
    - dask
    - scipy
    - scikit-image
    - matplotlib
    - nose
    - stsci.imagestats
    - stsci.tools
    - setuptools
    - numpy x.x
    - python x.x
source:
    git_url: https://github.com/jhunkeler/acstools
    git_branch: setuptools-conversion
test:
    commands:
    - acs_destripe --help
    - acs_destripe_plus --help
    imports:
    - acstools
