# Update data pack version as required
{% set name = 'webbpsf' %}
{% set version = environ.get("GIT_DESCRIBE_TAG", "0.0.0")
    +".dev"
    +environ.get("GIT_DESCRIBE_NUMBER", "0") %}
{% set number = '0' %}
{% set tag = GIT_DESCRIBE_TAG %}

about:
    home: https://github.com/mperrin/webbpsf
    license: BSD
    summary: webbpsf
build:
    number: {{ number }}
    preserve_egg_dir: 'True'
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - nose
    - astropy >=1.1
    - numpy x.x
    - scipy
    - matplotlib
    - poppy
    - six [py27]
    - webbpsf-data ==0.4.1
    - setuptools
    - python x.x
    run:
    - nose
    - astropy >=1.1
    - numpy x.x
    - scipy
    - matplotlib
    - poppy
    - six [py27]
    - webbpsf-data ==0.4.1
    - setuptools
    - python x.x
source:
    git_url: https://github.com/mperrin/webbpsf
test:
    commands:
    - WEBBPSF_PATH=$PREFIX/share/webbpsf-data python -c 'import webbpsf'
