{% set name = 'stsci.sphinxext' %}
{% set version = environ.get("GIT_DESCRIBE_TAG", "0.0.0")
    +".dev"
    +environ.get("GIT_DESCRIBE_NUMBER", "0") %}
{% set number = '0' %}

about:
    home: https://github.com/jhunkeler/stsci.sphinxext
    license: GPL
    summary: stsci.sphinxext
build:
    number: {{ number }}
    preserve_egg_dir: 'yes'
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - astropy
    - matplotlib
    - nose
    - numpydoc
    - relic >=1.0.3
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - astropy
    - matplotlib
    - nose
    - numpydoc
    - numpy x.x
    - python x.x
source:
    git_url: https://github.com/jhunkeler/stsci.sphinxext
    git_branch: setuptools-conversion
test:
    imports:
    - stsci.sphinxext
