{% set name = 'cube-tools' %}
{% set version = environ.get("GIT_DESCRIBE_TAG", "0.0.0")
    +".dev"
    +environ.get("GIT_DESCRIBE_NUMBER", "0") %}
# Override due to lack of tags
{% set version = '0.0.1' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/cube-tools
    license: BSD
    summary: cube-tools
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - glueviz
    - specview
    - pyqtgraph
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - glueviz
    - specview
    - pyqtgraph
    - numpy x.x
    - python x.x
source:
    git_url: https://github.com/spacetelescope/cube-tools
test:
    imports:
    - cube_tools
